### ISSUE TITLE
[LibC] Implement 'clock_gettime', 'clock_settime', 'clock_getres'

### ISSUE THREAD

**Issue by nathanLoretan** [insane-adding-machines/frosted#116]
Hello, I try to use the function clock_gettime(). I define _POSIX_TIMERS and I include <time.h> but I always have the error: undefined reference to 'clock_gettime'.

**Comment by danielinux** [comment]
Hi! In fact clock_gettime/clock_settime/clock_getres are not yet implemented in libC.

I will turn this issue in a feature request and take care of it ASAP. Meanwhile, any chance you can use gettimeofday() ?

Thanks

d

**Comment by danielinux** [comment]
Not fixed yet for us, so better not close it @nathanLoretan

**Comment by brabo** [comment]
ok, this is next up on my frosted-calendar!

**Comment by brabo** [comment]
@nathanLoretan what resolution are you guys expecting clock_gettime() to have? assuming XSI-conformance or?

**Comment by nathanLoretan** [comment]
CLOCK_REALTIME

**Comment by brabo** [comment]
@nathanLoretan that is a clock, not the resolution. i ask because of:
"Although the value of CLOCKS_PER_SEC is required to be 1 million on all XSI-conformant systems, it may be variable on other systems, and it should not be assumed that CLOCKS_PER_SEC is a compile-time constant"
if you assume 1 million per second, it may cause issues as our system clock resolution is only 1000/sec, i.e. millisecond resolution, and i noticed there is no clock_getres() call in uGFX to determine what resolution the system has.

**Comment by danielinux** [comment]
@brabo we should stick with 1ms resolution for these calls anyhow

**Comment by brabo** [comment]
@nathanLoretan done, closing this issue ;)

**Comment by brabo** [comment]
@nathanLoretan note, just include sys/time.h for now, not time.h as posix specifies.

**Comment by danielinux** [comment]
Related to #120

**Comment by brabo** [comment]
time.h is there now.
